
import json
import os

notebook_name = "HuggingFace_MCQ_Extractor.ipynb"

# --- Cell Content Definitions ---

# Cell 1: Setup & Imports
cell_1_source = [
    "# Cell 1: Setup & Imports\n",
    "# Install necessary libraries if not already installed\n",
    "!pip install streamlit pydantic pillow pymupdf requests openai\n",
    "\n",
    "import os\n",
    "import json\n",
    "import re\n",
    "import time\n",
    "import base64\n",
    "import shutil\n",
    "import tempfile\n",
    "from pathlib import Path\n",
    "from typing import List, Optional, Dict, Union\n",
    "from io import BytesIO\n",
    "\n",
    "import fitz  # PyMuPDF\n",
    "from PIL import Image\n",
    "from pydantic import BaseModel, Field, ValidationError\n",
    "from openai import OpenAI"
]

# Cell 2: Pydantic Schemas
cell_2_source = [
    "# Cell 2: Pydantic Schemas\n",
    "# Defining the data structures for extraction\n",
    "\n",
    "class QuestionData(BaseModel):\n",
    "    id: int = Field(description=\"Literal printed question number.\")\n",
    "    chapter: str = Field(default=\"Physical World & Measurement\", description=\"The chapter name, default or inferred.\")\n",
    "    question: str\n",
    "    question_latex: str\n",
    "    image_url: str = Field(default=\"\", description=\"Descriptive tag if diagram is present.\")\n",
    "    options: List[str]\n",
    "    difficulty: str = Field(description=\"Infer the difficulty: 'easy', 'medium', or 'hard'.\")\n",
    "    is_fragment: bool = Field(default=False, description=\"True if the question is incomplete and continues onto the next page.\")\n",
    "\n",
    "class KeyData(BaseModel):\n",
    "    id: int\n",
    "    answer_option: str = Field(description=\"The single correct option letter (A, B, C, or D).\")\n",
    "\n",
    "class SolutionData(BaseModel):\n",
    "    id: int\n",
    "    solution: str = Field(description=\"The detailed solution, all math in $$. Use \\\\n for newlines.\")\n",
    "    is_fragment: bool = Field(default=False, description=\"True if the solution is incomplete and continues onto the next page.\")\n",
    "\n",
    "class IntermediateResult(BaseModel):\n",
    "    \"\"\"The ROOT schema used for every API call.\"\"\"\n",
    "    questions: List[QuestionData] = []\n",
    "    answer_keys: List[KeyData] = []\n",
    "    solutions: List[SolutionData] = []\n",
    "\n",
    "class FinalMCQ(BaseModel):\n",
    "    id: int\n",
    "    chapter: str\n",
    "    question: str\n",
    "    question_latex: str\n",
    "    image_url: str\n",
    "    options: List[str]\n",
    "    answer: str\n",
    "    solution: str\n",
    "    difficulty: str\n",
    "    marks: int = Field(default=4)"
]

# Cell 3: System Prompt
cell_3_source = [
    "# Cell 3: System Prompt\n",
    "# Detailed instructions for the multimodal model\n",
    "\n",
    "SYSTEM_INSTRUCTION = \"\"\"\n",
    "You are an expert academic data extraction engine specializing in Physics, Chemistry, Mathematics, Biology exams.\n",
    "Your task is to analyze the provided single image of an exam page and accurately extract all distinct data fragments present: **Questions, Answer Keys, or Detailed Solutions.**\n",
    "\n",
    "Your output MUST populate the corresponding lists (questions, answer_keys, or solutions) within the 'IntermediateResult' schema. If a section is absent from the image, return its list as an empty array ([]).\n",
    "\n",
    "--- PRIMARY EXTRACTION RULES (ID Mapping) ---\n",
    "1.  **Question/Solution ID Source:** The 'id' field MUST be the **literal printed number** (e.g., 1, 17, 30) visible in the image.\n",
    "2.  **ID Continuity:** The literal ID must be used consistently across all three schemas.\n",
    "\n",
    "--- STRENGTHENED CONTENT EXTRACTION RULES ---\n",
    "1.  **Fragment Flagging (CRITICAL):**\n",
    "    * If a Question or Solution starts on this page but is clearly **truncated** or **incomplete** (e.g., the text abruptly stops mid-sentence, options are missing, or the solution steps are cut off at the bottom of the image), set the `is_fragment` field to `true`.\n",
    "    * If the question/solution is complete on this page, set `is_fragment` to `false`.\n",
    "2.  **Questions & Options (Content):** Extract the **full body, options, and question_latex**.\n",
    "3.  **Answer Keys (Arrangement):** Extract only the question ID and the final letter/option (A, B, C, D).\n",
    "4.  **Solutions:** Extract the full step-by-step text for the `solution` field.\n",
    "\n",
    "--- STRICT FORMATTING & QUALITY RULES ---\n",
    "1.  **JSON Output:** The entire output MUST be a JSON object that strictly conforms to the 'IntermediateResult' Pydantic schema.\n",
    "2.  **LaTeX Requirement:** All mathematical expressions, physics formulas, units (e.g., $\\\\text{kg}$), and dimensional analysis MUST be translated into standard **LaTeX format** and **strictly enclosed in single dollar signs ($$)**.\n",
    "3.  **Solution Formatting:** In the `solution` field, replace native line breaks with the LaTeX newline command ('\\\\n').\n",
    "4.  **Image URL:** Set the `image_url` to a **descriptive tag** (e.g., 'Image of bridge circuit diagram') if a diagram/graph is present. Otherwise, use an empty string (\"\").\n",
    "5.  **Placeholders:** If an MCQ detail (like an option text or solution body) is unclear or missing, use an empty string (`\"\"`) as a placeholder.\n",
    "\"\"\""
]

# Cell 4: PDF to Image Conversion
cell_4_source = [
    "# Cell 4: PDF to Image Conversion\n",
    "# Utility functions for handling PDF files\n",
    "\n",
    "def natural_sort_key(s):\n",
    "    \"\"\"Sorts file names naturally (e.g., page_9 before page_10).\"\"\"\n",
    "    return [int(text) if text.isdigit() else text.lower() for text in re.split('([0-9]+)', s.name)]\n",
    "\n",
    "def convert_pdfs_to_images(pdf_paths: List[Path], output_dir: Path, dpi: int = 300) -> List[Path]:\n",
    "    \"\"\"Converts PDF pages to PNG images and saves them to a temporary directory.\"\"\"\n",
    "    all_image_paths = []\n",
    "    zoom_factor = dpi / 72\n",
    "    matrix = fitz.Matrix(zoom_factor, zoom_factor)\n",
    "\n",
    "    for pdf_path in pdf_paths:\n",
    "        try:\n",
    "            doc = fitz.open(pdf_path)\n",
    "            for page_num in range(len(doc)):\n",
    "                page = doc.load_page(page_num)\n",
    "                pix = page.get_pixmap(matrix=matrix, alpha=False)\n",
    "                \n",
    "                output_filename = f\"{pdf_path.stem}_page_{page_num + 1}.png\"\n",
    "                output_path = output_dir / output_filename\n",
    "                \n",
    "                pix.save(output_path)\n",
    "                all_image_paths.append(output_path)\n",
    "            doc.close()\n",
    "        except Exception as e:\n",
    "            print(f\"Error converting PDF {pdf_path.name}: {e}\")\n",
    "            continue\n",
    "    return all_image_paths"
]

# Cell 5: Multimodal API Core
cell_5_source = [
    "# Cell 5: Multimodal API Core\n",
    "# Functions to interact with the Hugging Face Inference API via OpenAI Client\n",
    "\n",
    "def encode_image_to_base64(image_path: Path) -> str:\n",
    "    \"\"\"Encodes an image file to a base64 string.\"\"\"\n",
    "    with open(image_path, \"rb\") as image_file:\n",
    "        return base64.b64encode(image_file.read()).decode('utf-8')\n",
    "\n",
    "def process_image_with_ai(image_path: Path, client: OpenAI, system_instruction: str, model_id: str = \"multimodal-model-on-hf\", retries: int = 5, initial_delay: int = 5) -> Optional[IntermediateResult]:\n",
    "    \"\"\"\n",
    "    Sends a single image to the multimodal model for structured extraction.\n",
    "    Handles 429 Rate Limits with exponential backoff.\n",
    "    \"\"\"\n",
    "    base64_image = encode_image_to_base64(image_path)\n",
    "    \n",
    "    # OpenAI Chat Completion format for Multimodal input\n",
    "    messages = [\n",
    "        {\"role\": \"system\", \"content\": system_instruction},\n",
    "        {\n",
    "            \"role\": \"user\",\n",
    "            \"content\": [\n",
    "                {\"type\": \"text\", \"text\": \"Extract all questions, solutions, and keys from this image according to the schema.\"},\n",
    "                {\n",
    "                    \"type\": \"image_url\",\n",
    "                    \"image_url\": {\n",
    "                        \"url\": f\"data:image/png;base64,{base64_image}\"\n",
    "                    }\n",
    "                }\n",
    "            ]\n",
    "        }\n",
    "    ]\n",
    "\n",
    "    for attempt in range(retries):\n",
    "        try:\n",
    "            # Note: We enforce JSON format via response_format if supported, or rely on system prompt\n",
    "            response = client.chat.completions.create(\n",
    "                model=model_id,\n",
    "                messages=messages,\n",
    "                max_tokens=4000,\n",
    "                # response_format={\"type\": \"json_object\"} # Uncomment if strict JSON mode is supported by the HF model\n",
    "            )\n",
    "            \n",
    "            content = response.choices[0].message.content\n",
    "            \n",
    "            # Clean up potential Markdown code blocks if the model adds them\n",
    "            if \"```json\" in content:\n",
    "                content = content.replace(\"```json\", \"\").replace(\"```\", \"\")\n",
    "            elif \"```\" in content:\n",
    "                content = content.replace(\"```\", \"\")\n",
    "                \n",
    "            # Validate and Parse\n",
    "            data = IntermediateResult.model_validate_json(content)\n",
    "            return data\n",
    "            \n",
    "        except Exception as e:\n",
    "            error_str = str(e)\n",
    "            if \"429\" in error_str or \"Rate limit\" in error_str:\n",
    "                wait_time = initial_delay * (2 ** attempt)\n",
    "                print(f\"Rate limit hit for {image_path.name}. Retrying in {wait_time}s...\")\n",
    "                time.sleep(wait_time)\n",
    "                continue\n",
    "            else:\n",
    "                print(f\"API Error processing {image_path.name}: {e}\")\n",
    "                return None\n",
    "    \n",
    "    print(f\"Failed to process {image_path.name} after {retries} retries.\")\n",
    "    return None"
]

# Cell 6: Stitching and Merging Logic
cell_6_source = [
    "# Cell 6: Stitching and Merging Logic\n",
    "# Logic to combine fragmented questions/solutions across pages\n",
    "\n",
    "def stitch_fragments(data_list: List[Union[QuestionData, SolutionData]]) -> List[Union[QuestionData, SolutionData]]:\n",
    "    grouped_data: Dict[int, List[Union[QuestionData, SolutionData]]] = {}\n",
    "    for item in data_list:\n",
    "        grouped_data.setdefault(item.id, []).append(item)\n",
    "\n",
    "    stitched_list = []\n",
    "    \n",
    "    for item_id, fragments in grouped_data.items():\n",
    "        primary_item = fragments[0]\n",
    "        is_question = isinstance(primary_item, QuestionData)\n",
    "\n",
    "        for subsequent_item in fragments[1:]:\n",
    "            if is_question:\n",
    "                primary_item.question += \" \" + subsequent_item.question\n",
    "                primary_item.options.extend(subsequent_item.options)\n",
    "                if subsequent_item.question_latex and subsequent_item.question_latex != primary_item.question_latex:\n",
    "                     primary_item.question_latex += \" \\\\text{ [Cont.] } \" + subsequent_item.question_latex\n",
    "                if subsequent_item.image_url and subsequent_item.image_url != primary_item.image_url:\n",
    "                    primary_item.image_url += \" | \" + subsequent_item.image_url\n",
    "            else:\n",
    "                primary_item.solution += subsequent_item.solution\n",
    "        \n",
    "        primary_item.is_fragment = False \n",
    "        stitched_list.append(primary_item)\n",
    "\n",
    "    return stitched_list\n",
    "\n",
    "def merge_data(all_q_data, all_key_data, all_sol_data) -> List[FinalMCQ]:\n",
    "    stitched_q_data = stitch_fragments(all_q_data)\n",
    "    stitched_sol_data = stitch_fragments(all_sol_data)\n",
    "\n",
    "    question_map = {}\n",
    "    key_map = {k.id: k.answer_option for k in all_key_data}\n",
    "    solution_map = {s.id: s.solution for s in stitched_sol_data}\n",
    "\n",
    "    for q_data in stitched_q_data:\n",
    "        if q_data.id not in question_map:\n",
    "            question_map[q_data.id] = q_data\n",
    "\n",
    "    final_mcqs = []\n",
    "    sorted_ids = sorted(question_map.keys())\n",
    "    final_id_counter = 1\n",
    "\n",
    "    for original_id in sorted_ids:\n",
    "        q_data = question_map[original_id]\n",
    "        option_letter = key_map.get(original_id, \"\")\n",
    "        answer_string = \"\"\n",
    "        \n",
    "        if option_letter and q_data.options:\n",
    "            option_index_map = {'A': 0, 'B': 1, 'C': 2, 'D': 3}\n",
    "            index = option_index_map.get(option_letter.upper())\n",
    "            if index is not None and 0 <= index < len(q_data.options):\n",
    "                answer_string = q_data.options[index]\n",
    "            \n",
    "        mcq = FinalMCQ(\n",
    "            id=final_id_counter,\n",
    "            chapter=q_data.chapter,\n",
    "            question=q_data.question,\n",
    "            question_latex=q_data.question_latex,\n",
    "            image_url=q_data.image_url,\n",
    "            options=q_data.options,\n",
    "            answer=answer_string, \n",
    "            solution=solution_map.get(original_id, \"\"),\n",
    "            difficulty=q_data.difficulty,\n",
    "            marks=4\n",
    "        )\n",
    "        final_mcqs.append(mcq)\n",
    "        final_id_counter += 1\n",
    "        \n",
    "    return final_mcqs"
]

# Cell 7: Main Execution Logic
cell_7_source = [
    "# Cell 7: Main Execution Logic\n",
    "# ---------------------------------------------------------\n",
    "# CONFIGURATION\n",
    "# ---------------------------------------------------------\n",
    "# Placeholder text for file path - Replace with your actual PDF path\n",
    "sample_pdf_path = \"cetchap1.pdf\"\n",
    "\n",
    "# Hugging Face Configuration\n",
    "HF_TOKEN = os.getenv(\"HF_TOKEN\") # Ensure this is set in your environment\n",
    "MODEL_NAME = \"multimodal-model-on-hf\"\n",
    "# Route to the model's OpenAI-compatible endpoint\n",
    "HF_API_BASE = f\"https://api-inference.huggingface.co/models/{MODEL_NAME}/v1/\"\n",
    "\n",
    "if not HF_TOKEN:\n",
    "    print(\"WARNING: HF_TOKEN is not set. Please set it before running.\")\n",
    "\n",
    "# Initialize OpenAI Client pointing to Hugging Face\n",
    "client = OpenAI(\n",
    "    base_url=HF_API_BASE,\n",
    "    api_key=HF_TOKEN\n",
    ")\n",
    "\n",
    "# ---------------------------------------------------------\n",
    "# PIPELINE EXECUTION\n",
    "# ---------------------------------------------------------\n",
    "if os.path.exists(sample_pdf_path):\n",
    "    print(f\"Starting processing for: {sample_pdf_path}\")\n",
    "    \n",
    "    # 1. Setup Dirs\n",
    "    temp_dir = Path(\"temp_processing_hf\")\n",
    "    if temp_dir.exists():\n",
    "        shutil.rmtree(temp_dir)\n",
    "    temp_dir.mkdir()\n",
    "    \n",
    "    images_dir = temp_dir / \"images\"\n",
    "    images_dir.mkdir()\n",
    "    \n",
    "    # 2. Convert PDF\n",
    "    print(\"Phase 1: Converting to Images...\")\n",
    "    image_paths = convert_pdfs_to_images([Path(sample_pdf_path)], images_dir)\n",
    "    sorted_images = sorted(image_paths, key=natural_sort_key)\n",
    "    \n",
    "    # 3. AI Extraction Loop\n",
    "    print(f\"Phase 2: Extracting data from {len(sorted_images)} images...\")\n",
    "    all_q, all_k, all_s = [], [], []\n",
    "    \n",
    "    for i, img_path in enumerate(sorted_images):\n",
    "        print(f\"  - Processing {img_path.name}...\")\n",
    "        result = process_image_with_ai(img_path, client, SYSTEM_INSTRUCTION, model_id=MODEL_NAME)\n",
    "        if result:\n",
    "            all_q.extend(result.questions)\n",
    "            all_k.extend(result.answer_keys)\n",
    "            all_s.extend(result.solutions)\n",
    "        \n",
    "        # Polite delay\n",
    "        time.sleep(2)\n",
    "\n",
    "    # 4. Merge\n",
    "    print(\"Phase 3: Merging Results...\")\n",
    "    final_data = merge_data(all_q, all_k, all_s)\n",
    "    \n",
    "    # 5. Output\n",
    "    output_json = [item.model_dump() for item in final_data]\n",
    "    print(\"\\n--- EXTRACTION COMPLETE ---\\n\")\n",
    "    print(json.dumps(output_json, indent=2, ensure_ascii=False))\n",
    "    \n",
    "    # Cleanup\n",
    "    # shutil.rmtree(temp_dir) # Uncomment to clean up\n",
    "else:\n",
    "    print(f\"File not found: {sample_pdf_path}. Please upload the PDF to the notebook directory.\")\n"
]

# Compose Notebook
notebook_content = {
    "cells": [
        {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": cell_1_source},
        {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": cell_2_source},
        {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": cell_3_source},
        {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": cell_4_source},
        {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": cell_5_source},
        {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": cell_6_source},
        {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": cell_7_source}
    ],
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "codemirror_mode": {"name": "ipython", "version": 3},
            "file_extension": ".py",
            "mimetype": "text/x-python",
            "name": "python",
            "nbconvert_exporter": "python",
            "pygments_lexer": "ipython3",
            "version": "3.x"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 5
}

with open(notebook_name, "w", encoding="utf-8") as f:
    json.dump(notebook_content, f, indent=1)

print(f"Successfully created {notebook_name}")
